# Generated by Django 5.2.8 on 2025-12-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_conversationhistory_schedulinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=50),
        ),
    ]
